[server]
# The port where the server will listen for client and browser connections
port = 8501

# The IP address where the server will listen for client and browser connections
headless = false
address = "0.0.0.0"

# Run the server in headless mode
runOnSave = true

# Automatically rerun script when the source code is changed
allowRunOnSave = true

# Max upload size in MB
maxUploadSize = 200

# Enable CORS for API calls
enableCORS = false

# Enable XSRF protection
enableXsrfProtection = true

[browser]
# Internet address where users should point their browsers to connect to the app
serverAddress = "0.0.0.0"

# Whether to send usage statistics to Streamlit
gatherUsageStats = false

# Port where users should point their browsers to connect to the app
serverPort = 8501

[theme]
# The preset Streamlit theme that your custom theme inherits from
base = "light"

# Primary accent color for interactive elements
primaryColor = "#667eea"

# Background color for the main content area
backgroundColor = "#ffffff"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#f0f2f6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app
font = "sans serif"

[client]
# Whether to enable live theme editing
caching = true

# Display a toolbar at the top of the app with options to record screencasts
showErrorDetails = true

# Controls whether uncaught app exceptions are displayed in the browser
toolbarMode = "auto"